name: Quality Gates for Firebase Functions on PR
"on":
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/functions/**"
      - ".github/workflows/firebase-functions-*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies & build functions
        run: yarn install --frozen-lockfile && yarn build:functions
