name: Deploy to Firebase Functions on merge
"on":
  pull_request:
    branches:
      - develop
    paths:
      - "packages/functions/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - run: yarn install --frozen-lockfile && yarn run build:functions
