name: Deploy to Firebase Functions on merge to main branch
"on":
  push:
    branches:
      - main
    paths:
      - "packages/functions/**"
      - ".github/workflows/firebase-functions-*.yml"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.5.2
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EPMGCIP_UVA }}
