name: Build Firebase Functions on PR
"on":
  pull_request:
    branches:
      - develop
    paths:
      - "packages/functions/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - run: yarn install --frozen-lockfile && yarn run build:functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.5.1
        with:
          args: deploy --only functions --debug
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EPMGCIP_UVA_DEVELOP }}
